

[tool.ruff]
include = ["*.py"]
# Exclude a variety of commonly ignored directories.
line-length = 120
target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["F", "E4", "E7", "E9", "SIM", "PTH", "PERF"]
# ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
# fixable = ["ALL"]
# unfixable = []

# Allow unused variables when underscore-prefixed.
#dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
# quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
# indent-style = "space"

# Like Black, respect magic trailing commas.
# skip-magic-trailing-comma = false


